S4F3TY@jms MINGW64 ~/Desktop/blockchain-privacy-preserving (main)
$ ls -F
LICENSE  LICENSE-APACHE  LICENSE-MIT  README.md  src/  tests/

S4F3TY@jms MINGW64 ~/Desktop/blockchain-privacy-preserving (main)
$